reporting:
  include_experiments: ["B2", "B21", "B22"]
  max_steps: 20000
  metrics_root: "data/08_reporting"

  approx_params:
    B2:  7200000
    B21: 7200000
    B22: 7200000

  # No non-EMA vs EMA pairs today; leave empty so the plot shows "No valid EMA pairs".
  ema_pairs: []

  output_paths:
    val_loss:        "data/08_reporting/plots/B2+/val_loss_vs_steps.png"
    size_vs_ppl:     "data/08_reporting/plots/B2+/size_vs_ppl.png"
    ema_vs_non_ema:  "data/08_reporting/plots/B2+/ema_vs_nonema.png"
    steps_saved:     "data/08_reporting/plots/B2+/steps_saved.png"
